name: pramod_portfolio
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  audioplayers: ^6.4.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.7
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  gap: ^3.0.1
  get: ^4.7.2
  google_fonts: ^6.2.1
  icons_plus: ^5.0.0
  lottie: ^3.3.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/card_slider/
    - assets/mp3/
    
