// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWGD0U7RzrFebOzQ-wa7E87Se_wzvX6i0',
    appId: '1:177492266412:web:b4760a54d9f4c3c62efe09',
    messagingSenderId: '177492266412',
    projectId: 'pramod-portfolio-120ad',
    authDomain: 'pramod-portfolio-120ad.firebaseapp.com',
    storageBucket: 'pramod-portfolio-120ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCISRpjm2_61U7pkducmwzFiGdRYmBGkg',
    appId: '1:177492266412:android:80abc17d998c13c12efe09',
    messagingSenderId: '177492266412',
    projectId: 'pramod-portfolio-120ad',
    storageBucket: 'pramod-portfolio-120ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDUyoApZshSVQ6uD6RmUnmlVxsL374iUs',
    appId: '1:177492266412:ios:5ac2a88763760c222efe09',
    messagingSenderId: '177492266412',
    projectId: 'pramod-portfolio-120ad',
    storageBucket: 'pramod-portfolio-120ad.firebasestorage.app',
    iosBundleId: 'com.example.pramodPortfolio',
  );
}
