name: Deploy Flutter Web to Firebase Hosting
on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      flutter-cache: ${{ steps.cache-flutter.outputs.cache-hit }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Flutter SDK
        id: cache-flutter
        uses: actions/cache@v4
        with:
          path: ~/.flutter
          key: flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze & Test
        run: |
          flutter analyze
          flutter test

      - name: Build Flutter Web
        run: flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true --tree-shake-icons

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: build/web

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRAMOD_PORTFOLIO_120AD }}
          channelId: live
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
